name: ecommerce
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  auto_animated: null
  badges: null
  cached_network_image: null
  cloud_firestore: null
  dartz: null
  device_preview: null
  dropdown_search: null
  firebase_core: null
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_local_notifications: null
  flutter_polyline_points: null
  flutter_svg: null
  fluttericon: null
  font_awesome_flutter: null
  geocoding: null
  geolocator: null
  get: null
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_maps_flutter: null
  google_sign_in: null
  grouped_list: null
  http: null
  image_picker: null
  image_pickers: null
  intl: null
  jiffy: null
  lottie: ^2.7.0
  path: null
  qr_flutter: null
  responsive_builder: null
  scan: null
  shared_preferences: null
  show_up_animation: null
  smooth_page_indicator: ^1.1.0
  sqflite: null
  url_launcher: null

dev_dependencies:
  flutter_launcher_icons: 
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/onborading/
    
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
